# Site settings
title: Laharl
description: My personal homepage

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prince-laharl.github.io" # the base hostname & protocol for your site

author:
  fullname: Prince Laharl
  github: Prince-Laharl

markdown: kramdown
